version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: 'exit 0'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"