version: '3.3'

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: 'exit 0'

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: on-failure

  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - mailhog
    restart: on-failure
